#!/usr/bin/php
<?php

require_once "nastroje.php" ;
require_once "transpilator.php" ;
require_once "zvladac_oznameni.php" ;

$kratke_moznosti = "" ;
$kratke_moznosti .= "z::" ;
$kratke_moznosti .= "v::" ;
$kratke_moznosti .= "h" ;
$kratke_moznosti .= "s" ;

$dlouhe_moznosti = array(
    "help"
) ;

$konfigurace = getopt($kratke_moznosti, $dlouhe_moznosti) ;

if (array_key_exists("h", $konfigurace) || array_key_exists("help", $konfigurace)) {
    echo <<<EOT
použití: ophp [možnosti]

Bo neni cas pyco

možnosti:
    -h, --help      Zobrazí tuto nápovědu
    -z              Určí zdrojovou složku s .ophp soubory
    -v              Určí výslednou složku s vygenerovanými .php soubory
    -s              Mód slitování, vypne cenzuru PHP tokenů

EOT ;
    return ;
}

echo "spouštění transpilátoru\n" ;

$zdrojova_slozka = "" ;
if (array_key_exists("z", $konfigurace))
    $zdrojova_slozka = $konfigurace["z"] ;
$zdrojova_slozka = normalizovat_cestu($zdrojova_slozka) ;
echo "zdrojová složka: $zdrojova_slozka\n" ;

$vystupni_slozka = "" ;
if (array_key_exists("v", $konfigurace))
    $vystupni_slozka = $konfigurace["v"] ;
$vystupni_slozka = normalizovat_cestu($vystupni_slozka) ;
echo "výstupní složka: $vystupni_slozka\n" ;

$slitovani = array_key_exists("s", $konfigurace) ;
$slitovani_text = $slitovani ? "fajne" : "nyt" ;
echo "mód slitování: $slitovani_text\n" ;

echo "\n" ;

$soubory = projit_slozku($zdrojova_slozka) ;
$ophp_soubory = array_filter($soubory, function($ophp_soubor) { return str_ends_with($ophp_soubor, ".ophp") ; }) ;
foreach ($ophp_soubory as $ophp_soubor) {
    $ophp_soubor_bez_slozky = mb_substr($ophp_soubor, mb_strlen($zdrojova_slozka)) ;
    $php_soubor_bez_slozky = nahradit_koncovku($ophp_soubor_bez_slozky, ".ophp", ".php") ;
    $php_soubor = $vystupni_slozka . $php_soubor_bez_slozky ;
    
    $prefix = "[$ophp_soubor_bez_slozky] " ;

    $ophp_kod = file_get_contents($ophp_soubor) ;
    $transpilator = new Transpilator($ophp_kod) ;
    $php_kod = $transpilator->transpilovat(new ZvladacOznameni($slitovani, $prefix)) ;

    $slozka = dirname($php_soubor) ;
    if (!file_exists($slozka))
        mkdir($slozka, 0777, true) ;
    
    file_put_contents($php_soubor, $php_kod) ;
}

echo "\n" ;
echo "dokončeno\n" ;
