#!/usr/bin/php
<?php

require_once "nastroje.php" ;
require_once "transpilator.php" ;

$kratke_moznosti = "" ;
$kratke_moznosti .= "z::" ;
$kratke_moznosti .= "v::" ;
$kratke_moznosti .= "h" ;
$kratke_moznosti .= "s" ;

$dlouhe_moznosti = array(
    "help"
) ;

$konfigurace = getopt($kratke_moznosti, $dlouhe_moznosti) ;

if (array_key_exists("h", $konfigurace) || array_key_exists("help", $konfigurace)) {
    echo <<<EOT
použití: ophp [možnosti]

Bo neni cas pyco

možnosti:
    -h, --help      Zobrazí tuto nápovědu
    -z              Určí zdrojovou složku s .ophp soubory
    -v              Určí výslednou složku s vygenerovanými .php soubory
    -s              Mód slitování, vypne cenzuru PHP tokenů

EOT ;
    return ;
}

$zdrojova_slozka = "" ;
if (array_key_exists("z", $konfigurace))
    $zdrojova_slozka = $konfigurace["z"] ;
$zdrojova_slozka = normalizovat_cestu($zdrojova_slozka) ;

$vystupni_slozka = "" ;
if (array_key_exists("v", $konfigurace))
    $vystupni_slozka = $konfigurace["v"] ;
$vystupni_slozka = normalizovat_cestu($vystupni_slozka) ;

$slitovani = array_key_exists("s", $konfigurace) ;

$soubory = projit_slozku($zdrojova_slozka) ;
foreach ($soubory as $ophp_soubor) {
    if (!str_ends_with($ophp_soubor, ".ophp"))
        continue ;

    $ophp_kod = file_get_contents($ophp_soubor) ;
    $transpilator = new Transpilator($ophp_kod) ;
    $php_kod = $transpilator->transpilovat($slitovani) ;

    $ophp_soubor_bez_slozky = mb_substr($ophp_soubor, mb_strlen($zdrojova_slozka)) ;
    $php_soubor_bez_slozky = nahradit_koncovku($ophp_soubor_bez_slozky, ".ophp", ".php") ;
    $php_soubor = $vystupni_slozka . $php_soubor_bez_slozky ;

    $slozka = dirname($php_soubor) ;
    if (!file_exists($slozka))
        mkdir($slozka, 0777, true) ;
    
    file_put_contents($php_soubor, $php_kod) ;
}
